### ISSUE TITLE
The url /notification/ (Notification listing) (Admin DataGrid Field Translation Support)

### ISSUE THREAD

**Issue by hb7777** [DigitalState/Platform-legacy#26]
We are missing the title content.

![notification-listing](https://cloud.githubusercontent.com/assets/15639389/22225595/02a3ef96-e191-11e6-83d9-5cd4c6b7d7e5.PNG)

**Comment by StephenOTT** [comment]
This is a issue with OroPlatform 1.x where the Admin datagrids dont have the translations in the Twig templates.  This has been fixed in 2.0.  We are evaluating pros and cons to preform OroPlatform 2.0 upgrade vs implement a app wide temp-patch to BAP 1.x

**Comment by Kshapova** [comment]
Hello
You can try this. 
Add template to your datagrid (section columns)
          
```
columns:
    title:
         label: My Label
         type: twig
         frontend_type: html
         template: MyBundle:Entity:datagrid/property/title.html.twig
         context:
               entity_provider: '@doctrine.orm.entity_manager'
```

And then dans datagrid/property/title.html.twig: 
```
{# title.html.twig #}

{% set entity = entity_provider.find('MyBundle:Entity', record.getValue('id')) %}

{{ entity.defaultTitle }}
```
